### ISSUE TITLE
missing icon in super+/ shortcut

### ISSUE THREAD

**Issue by ffathina** [bikass/kora#101]
idk what it called, but in pop os its called 'launch and switch app'. here for the difference kora icon with suru++ dark.
-kora icon-
![Screenshot from 2021-01-06 05-48-07](https://user-images.githubusercontent.com/73886598/103709116-74769b80-4fe4-11eb-9f63-5ebcc0a42347.png)
 
-suru++ dark-
![Screenshot from 2021-01-06 05-55-56](https://user-images.githubusercontent.com/73886598/103709152-8b1cf280-4fe4-11eb-96bd-5f0de4f73236.png)

*sorry for my bad english

**Comment by ffathina** [comment]
sorry for not being specific, as we can see there is red exclamation mark icon in my kora screenshot. and i thing it should be used icon that indicates its an apps just like in my suru++dark screenshot.

**Comment by bikass** [comment]
Yes, I understand what needs to be fixed, but I can not fix it if I don't know icons name.

**Comment by ffathina** [comment]
oh i dont know either sorry :(

**Comment by bikass** [comment]
Found it. Fix will be in next release or you can download from latest commits.
