### ISSUE TITLE
[Request] New Icons

### ISSUE THREAD

**Issue by btd1337** [bikass/kora#106]
- [x] **PDF Tricks**
Comment=A simple, efficient app for small manipulation of PDF files. Compress, split, merge and convert PDF.
Icon=com.github.muriloventuroso.pdftricks
[Icon Link](https://github.com/muriloventuroso/pdftricks/blob/master/data/icons/256/com.github.muriloventuroso.pdftricks.svg)

- [x] **KonbuCase**
Comment=Convert case in your text
Icon=com.github.ryonakano.konbucase
[Icon Link](https://github.com/ryonakano/konbucase/blob/master/data/icons/128/com.github.ryonakano.konbucase.svg)

- [x] **GameHub**
Comment=All your games in one place
Icon=com.github.tkashkin.gamehub
[Icon Link](https://github.com/tkashkin/GameHub/blob/master/data/icon/128.svg)

- [x] **Layouts**
Comment=GNOME 3 layout options
Icon=gnome-layout-switcher
[Icon Link](https://gitlab.manjaro.org/Chrysostomus/gnome-layout-switcher/-/blob/master/data/gnome-layout-switcher.svg)

- [x] **OpenJDK Java 15**
Comment=OpenJDK Java 15
Icon=java15-openjdk
[Icon Link]()

- [x] **Modelio**
Comment=The opensource modeling environment
Icon=modelio
[Icon Link](https://github.com/ModelioOpenSource/Modelio/blob/master/products/icons/modelio.ico)

- [x] **Gestures**
Comment=Modern, minimal GUI app for libinput-gestures
Icon=org.cunidev.gestures
[Icon Link]()

- [x] **Tour**
Icon=org.gnome.Tour
[Icon Link](https://gitlab.gnome.org/GNOME/gnome-tour/-/blob/master/data/icons/org.gnome.Tour.svg)

- [x] **TablePlus**
Comment=Modern, native, and friendly GUI tool for relational databases (Alpha)
Icon=tableplus
[Icon Link](https://tableplus.com/resources/favicons/apple-icon.png)

- [x] **VStudio**
Comment=Valentina Studio is the ultimate data management tool for database administrators
Icon=vstudio
[Icon Link](https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/c2/b7/c1/c2b7c161-8d26-7463-29e8-197f78fadbcf/Icon.png/230x0w.png)

- [x] **Web Apps**
Comment=Run websites as if they were apps
Icon=webapp-manager
[Icon Link](https://github.com/linuxmint/webapp-manager/blob/master/usr/share/icons/hicolor/scalable/apps/webapp-manager.svg)

---

Generated by [icons-missing-script](https://github.com/btd1337/icons-missing-script)

**Comment by bikass** [comment]
I made those icons. Two were already in theme.

**Comment by btd1337** [comment]
@bikass The icon `org.cunidev.gestures` is not present for me on `Kora 1.4.1`.

**Comment by btd1337** [comment]
@bikass Just the `tableplus` icon is missing.

**Comment by bikass** [comment]
Icon name for tableplus was wrong. Fixed.

**Comment by Digitalone1** [comment]
There's also the icon missing for SciTE text editor application.

But it's already done, please make a symlink `SciTE.svg` ---> `org.scintilla.SciTE.svg`

**Comment by Digitalone1** [comment]
And please @bikass can you update geany icon? The one used now is too generic.

Please, take inspiration by the official one: https://github.com/geany/geany/blob/master/icons/scalable/geany.svg

@btd1337 I'm reopening, please unsubscribe the notifications if you're not interested.

**Comment by bikass** [comment]
@Digitalone1 Made symlink and geany.

**Comment by Digitalone1** [comment]
@bikass I think the [original one](https://github.com/geany/geany/blob/master/icons/scalable/geany.svg) is better made. Can you make it more like the original with depth and shadows?

If you don't want to, we can still pick the original and place it in the theme as it is.

**Comment by bikass** [comment]
I copied original. Removed strokes and effects, because it doesn't fit with themes style.

**Comment by Digitalone1** [comment]
@bikass Much better, I like it. Thank you!
