### ISSUE TITLE
[Request] Colored folders 

### ISSUE THREAD

**Issue by btd1337** [bikass/kora#107]
Hi @bikass,

Would be possible create an option to generate theme with different folder colors?

Thanks in advance!

**Comment by bikass** [comment]
Hi, I think it should be done with some script? But I have no idea how to do it.

**Comment by btd1337** [comment]
@bikass Maybe this help you.

https://github.com/PapirusDevelopmentTeam/papirus-folders

**Comment by FotiadisM** [comment]
This would be a killer feature, the icons are really really good but the color choice for folders is kind of limited with only blue and gray.

**Comment by D3SOX** [comment]
I'd really like to see this feature. This would be especially nice in combination with the recently introduced KDE accent colors.
@btd1337 I think for Papirus it's easy because they just have to replace one color, but it in the case of Kora it's using a gradient which is not that easy to replace. At least, I don't know a way of doing so :thinking:  :raised_eyebrow:

**Comment by D3SOX** [comment]
Upon further research I found https://github.com/gusbemacbe/suru-plus-folders, and it also has some gradient folders in there
![image](https://user-images.githubusercontent.com/24937357/148980455-b985b97a-ccae-49cb-aeba-d2c149b93469.png)
but I think this just works by replacing the folder icons with another set, so it's not actually 100% customizable to any color.

**Comment by bikass** [comment]
Hi, I looked at Papirus icons. There are few colour choices, but these are pre-made. I think you just choose one of those, with some kind of script.
@D3SOX  I made few variants. You van find them here: [https://www.gnome-look.org/p/1256209](url)

**Comment by haoadoreorange** [comment]
@bikass Hi, would it be possible to include the variant in this repo 🫠  ? I use a script to automate pulling the latest.
