### ISSUE TITLE
Save All action identical as Save

### ISSUE THREAD

**Issue by Digitalone1** [bikass/kora#108]
I switched to dark theme and noticed that Save All is nearly identical as Save action icon, I can't distinguish them. I don't know if it's something specific to my display, I'd like to know other feedback.

I thought the same with light theme, but it seems more obvious with the dark one. Maybe it could be done in another way to distinguish more one from another.

![Schermata del 2021-02-03 12-39-47](https://user-images.githubusercontent.com/25790525/106742630-8ff1b800-661d-11eb-83ea-c39c97630911.png)
![Schermata del 2021-02-03 12-47-11](https://user-images.githubusercontent.com/25790525/106742933-f971c680-661d-11eb-9d5f-f4843c08c041.png)

Thanks.

**Comment by bikass** [comment]
Ok, I separated those two arrows little bit . Maybe it will be more distinguishable .

**Comment by Digitalone1** [comment]
@bikass It's better than before, but not very optimal. Since action icons are small, the result in not very clear when downscaled.

Maybe it's better to draw separate arrows not intersecting between them, like:

* https://www.flaticon.com/premium-icon/down-arrows_3314257
* https://www.flaticon.com/premium-icon/arrow-down_2990183
* https://www.flaticon.com/premium-icon/down-arrow_3042431

Or doing only one row, but in a different way

* https://www.flaticon.com/premium-icon/down-arrow_2697078
* https://www.flaticon.com/free-icon/arrow-down-inside-a-square_18643
* https://www.flaticon.com/free-icon/download_981962

What do you think?

**Comment by bikass** [comment]
I forgot to tell you that I did icon. I don't like it, but maybe it looks on in UI.

**Comment by Digitalone1** [comment]
Two separated arrows much better. Thank you @bikass.
