### ISSUE TITLE
Icons are not showing and selecting Kora as the Icons options under Tweaks breaks down the gnome3

### ISSUE THREAD

**Issue by bluecpp** [bikass/kora#110]
Using the master on github repository breaks down the gnome. Also no icons are shown in the sidebar nor in the show applications menu.

**Comment by amirnn** [comment]
Also tried the latest release and encountered the same situation.

**Comment by bikass** [comment]
Try updating themes icon cache.

**Comment by bikass** [comment]
I updated cache files in all folders. Try if this fixes issue.

**Comment by amirnn** [comment]
Thank you.
I'll report back shortly.
