### ISSUE TITLE
Finance icon is missing in POP!_shop

### ISSUE THREAD

**Issue by vinayakumarMurganoor** [bikass/kora#114]
The icon of Finance is not loaded in pop shop.
![image](https://user-images.githubusercontent.com/8676836/125393913-179bd980-e3a9-11eb-8404-3c7d0322227e.png)

**Comment by bikass** [comment]
Fixed. Try downloading new commit.

**Comment by vinayakumarMurganoor** [comment]
problem still persist.

**Comment by bikass** [comment]
works for me
![Screenshot from 2021-07-13 12-15-28](https://user-images.githubusercontent.com/8824269/125426278-dfa52db4-1af1-47a5-b962-b91a2218748f.png)

**Comment by vinayakumarMurganoor** [comment]
works now.
