### ISSUE TITLE
Missing icon in pop launcher on search

### ISSUE THREAD

**Issue by vinayakumarMurganoor** [bikass/kora#115]
I think the gear icon is missing in the pop os launch app.
![image](https://user-images.githubusercontent.com/8676836/125394103-72cdcc00-e3a9-11eb-9fe7-b7927e1e3515.png)

**Comment by bikass** [comment]
Fixed. Try downloading new commit.

**Comment by vinayakumarMurganoor** [comment]
problem still persist.

**Comment by bikass** [comment]
works for me
![Screenshot from 2021-07-13 12-15-28](https://user-images.githubusercontent.com/8824269/125426278-dfa52db4-1af1-47a5-b962-b91a2218748f.png)

**Comment by vinayakumarMurganoor** [comment]
hmm do not know what is going wrong, installed at system level '/usr/share/icons'.
and update the icons cache and restarted the system. I'm using Pop!_OS 21.04, is it a problem?

**Comment by vinayakumarMurganoor** [comment]
this works now!
