### ISSUE TITLE
Possible icon optimizations/additions

### ISSUE THREAD

**Issue by LeFloatyPancake** [bikass/kora#116]
1. The Firefox icon doesn't seem to resemble Kora's "calm" design (might just be me)
2. Icon request for GTK  Widget Factory `org.gtk.WidgetFactory4.svg` & `org.gtk.WidgetFactory3.svg`

Thanks for making the icon theme. It's really pleasing to look at.

**Comment by bikass** [comment]
Can you point to original icons? There are in theme differently named gtk4-widget-factory.svg

**Comment by LeFloatyPancake** [comment]
![tst](https://user-images.githubusercontent.com/83509112/125633266-9be7dd4e-77c4-4b7f-8388-4818239d1e00.png)

**Comment by LeFloatyPancake** [comment]
.
