### ISSUE TITLE
Fragments icon

### ISSUE THREAD

**Issue by Falav** [bikass/kora#118]
Hello, could you please add the Fragments icon?

It's a BitTorent client for Gnome.
[Project site](https://gitlab.gnome.org/World/Fragments)

Icon: [Icon link](https://gitlab.gnome.org/World/Fragments/-/blob/master/data/icons/hicolor/scalable/apps/de.haeckerfelix.Fragments.svg)

Thanks!

**Comment by bikass** [comment]
Hi, Fragments icon is added.
