### ISSUE TITLE
LibreOffice Calc icon doesn't match the other LibreOffice icons

### ISSUE THREAD

**Issue by tommy4st** [bikass/kora#120]
LibreOffice Calc has the calculator icon, which looks off and probably is not intended to look like this. I search this repo and couldn't find the libreoffice-calc.svg, only references to it. Maybe this could be the problem?

![image](https://user-images.githubusercontent.com/2656837/139920674-4f74527d-834b-409b-9bc9-d9fd09a923e0.png)

**Comment by bikass** [comment]
Hi, but your icons from different theme, except calculator. And it works on my end..
![Libre](https://user-images.githubusercontent.com/8824269/140031979-1d9293b8-00c4-4402-8ad2-9e04e750ca38.png)

**Comment by tommy4st** [comment]
Obviously a lot of icons are not display, but I cannot figure out why. I am using NixOS and there was an [issue](https://github.com/NixOS/nixpkgs/issues/45935) reported, which looks familiar. The only difference for me is, it never works. If you have some advice to pinpoint the problem, I would be grateful, if not you're free to close this issue.

**Comment by bikass** [comment]
Sorry, for not replying for so long you can try updating cache. Or install system wide. I remember in Plasma had similar problem. Issue was how you extract archive. Don't remember exactly, but maybe it was extracting via terminal that worked.
