### ISSUE TITLE
Helvum icon symlink

### ISSUE THREAD

**Issue by Digitalone1** [bikass/kora#122]
Hello @bikass. Helvum pipewire app should have `org.freedesktop.ryuukyu.Helvum.svg` symlinked to `helvum.svg`.

`helvum.svg` is symlinked to `qjackctl.svg`, but take in consideration to make a new one if you want. You can take inspiration from [here](https://gitlab.freedesktop.org/ryuukyu/helvum/-/tree/main/data/icons).

The original icon is [here](https://gitlab.freedesktop.org/ryuukyu/helvum/-/blob/main/data/icons/org.freedesktop.ryuukyu.Helvum.svg).

**Comment by bikass** [comment]
Hi, made helvum.svg and symlink.

**Comment by Digitalone1** [comment]
Nice work as always @bikass!
