### ISSUE TITLE
Missing "Show Password" icon

### ISSUE THREAD

**Issue by ArtyIF** [bikass/kora#124]
The "Show Password" icon is missing, at the very least in GNOME apps. It instead shows the missing icon.

![Password Hidden](https://user-images.githubusercontent.com/8017858/148357974-efd80ee3-2498-4e10-971f-24f46474194e.png)

![Password Shown](https://user-images.githubusercontent.com/8017858/148357792-9b781c2f-6ff6-472c-9dd4-8702ba71fdab.png)

**Comment by bikass** [comment]
Hi, there is icon for me on login screen and timeshift.
![Screenshot from 2022-01-06 12-08-44](https://user-images.githubusercontent.com/8824269/148366822-58bfe295-72e8-4f3f-8a66-8440cec9b6d3.jpg)

**Comment by Vistaus** [comment]
I can't reproduce this either. Every app is showing the Show Password icon for me.
