### ISSUE TITLE
preferences-system.svg - All similar appear jagged edges

### ISSUE THREAD

**Issue by 0pLuS0** [bikass/kora#131]
Hello,

First let me say, I really love your iconset, great job!

I have run into one issue when using either Kora, or Kora Light the icon you made for the Preferences, they display in apps with jagged edges all the way around the circle.

Here are two screen shots...

From gmtp;

![gmtp](https://user-images.githubusercontent.com/36190223/158760060-d860b02f-086a-4e3d-844c-27f51cb15a48.jpg)

From Kid3;

![kid3](https://user-images.githubusercontent.com/36190223/158760083-f93d6002-1d75-46fd-a1e6-3bc10b20d885.jpg)

I can actually see the jagged circle, it's very noticeable to me, even in these screen shots, and more noticeable on the desktop using the iconset.

I hope you can smooth out the edges cleaner, or change the look to something else.

THANKS

```P.S. After posting this, I noticed the Connect icon even at the bottom center has a small dimple. I'm not sure why the icons distort in apps, but when I look at them in Gimp, they look very clean, somehow in apps they get distorted, I'm assuming because they are a one size to scale, but they aren't scaling cleanly.```

**Comment by bikass** [comment]
Hi,

Icons are svg should scale properly.
GMTP - on my side looks good. Kid3 uses its own icons. What DE are you using?
![Screenshot from 2022-03-17 14-01-32](https://user-images.githubusercontent.com/8824269/158804924-56e2eb20-4b55-4a87-b67e-38b7b459966d.jpg)

**Comment by 0pLuS0** [comment]
It's hard to tell with the Dark Theme, try using a Light Theme and look very closely if you see anything.

I'm using Openbox, but I've used themes for years, I've never had any jagged icons before.

Even when I look at the icons in their directory in SpaceFM, I can see jagged edges and a dimple on the bottom of this icon.

Look at all the icons that are circles in light blue, they all appear very smooth around the edges, but the preferences-system.svg is jagged and the dimple along the bottom.

Looking at icons in their directories with the file manager, is not going to distort the view of the images.

![icons](https://user-images.githubusercontent.com/36190223/158913294-c137d715-d126-422c-88c5-47c3912b7563.jpg)

**Comment by bikass** [comment]
Icon has been updated. Maybe this will fix your issue.
