### ISSUE TITLE
edit-paste symlink conflict

### ISSUE THREAD

**Issue by a-bentofreire** [bikass/kora#137]
Hi
On kora, the edit-paste symlink:
https://github.com/bikass/kora/blob/master/kora/apps/scalable/edit-paste.svg 
points to https://github.com/bikass/kora/blob/master/kora/apps/scalable/diodon.svg
which overrides the correct this icon on the theme.
https://github.com/bikass/kora/blob/master/kora/actions/16/edit-paste.svg
That symlink makes a copy&paste icons on a typical application show the diodon instead of the edit-paste.
I have solved locally by deleting this symlink, but I would help other users if you could also delete the symlink from the theme.

Thank you

**Comment by bikass** [comment]
Hi, thanks for pointing out. I made fixes.

**Comment by a-bentofreire** [comment]
Hi. 
Thank you for the quick fix.
