### ISSUE TITLE
[Request] icon for wolfram Mathematica

### ISSUE THREAD

**Issue by xoyssama** [bikass/kora#139]
Hello
If it's possible to add a custom icon for wolfram Mathematica that would be great.
Thanks in advance!

**Comment by bikass** [comment]
Hi,

There is already icon wolfram-mathematica.svg . Or did they changed to different one? Could you point to original icon?

**Comment by xoyssama** [comment]
I'm not sure I'm new to this, but I think the icons are in this directory
/usr/local/Wolfram/Mathematica/13.0/SystemFiles/FrontEnd/SystemResources/X/
and called  App-32.png   App-64.png  App-128.png 



When I installed papirus icons, the icon did change, I searched for that icon in the papirus directory I have found it with two different names: mathematica.svg  and wolfram-mathematica.svg

**Comment by bikass** [comment]
Hi,
There are these icons in theme. Or they doesn't show up for you?
![Screenshot from 2022-05-26 10-16-19](https://user-images.githubusercontent.com/8824269/170438122-e0363160-beea-49f1-ad0a-38c334be796c.png)

**Comment by xoyssama** [comment]
I reinstalled Mathematica and it worked this time.

Thank you for your support @bikass

**Comment by bikass** [comment]
Good to hear :)
