### ISSUE TITLE
VSCodium icon

### ISSUE THREAD

**Issue by DrumYum** [bikass/kora#140]
Hi! 

I would like to kindly ask for an update of VSCodium icon. 
As I can see, the official one has changed to "blue tree" (you can check on https://vscodium.com/), but in Kora it's still the old one. 

Thanks for this great icon pack!

**Comment by bikass** [comment]
Hi,

Thank you! And I'm glad you like our icon theme. 
VSCodium icon is updated. You can find it in latest commit.
