### ISSUE TITLE
Text file icon in desktop is probabily wrong

### ISSUE THREAD

**Issue by novecentonove** [bikass/kora#142]
![immagine](https://user-images.githubusercontent.com/53484559/178464327-35e7c20c-5e7f-44fd-af0d-e200f3c86880.png)

The txt icon on the desktop and Nautilus window appears 'blank with borders'. (See the attachment)
I believe it should be color filled (as a pdf, or .sql file).

Other blank icons i see (by extensions) are: with no extension, .csv, .env, .drawio, .css, .html, .js..

**Comment by bikass** [comment]
Hi, 
It is strange .txt file is most common-basic file extension. And for me it shows up correctly. Same with .css
Did you tried to create new icon theme cache (file is in icon theme folder)

**Comment by novecentonove** [comment]
@bikass, thanks for the suggestion. I tried the executable file  -`create-new-icon-theme.cache.sh` - but nothing changed even with reboot. (I forgot to mention I'm usign Ubuntu 22.04, Gnome vers: 42.2, maybe it helps)
Anyway, I'll look around about this issue.
