### ISSUE TITLE
Changing the blue WeChat Icon to the green one

### ISSUE THREAD

**Issue by Yikai-Liao** [bikass/kora#146]
The blue wechat icon in kora is quite strange. What about changing it to the green one. 
Here is the one used in kora now:

<img width="256" alt="AppIcon" src="https://user-images.githubusercontent.com/110762732/205419149-1021232a-ce15-4bb2-898b-9e67c4589934.svg">

Here is the icon I export from the wechat icon on mac.

<img width="256" alt="AppIcon" src="https://user-images.githubusercontent.com/110762732/205260554-f5d60227-4d42-44d0-a4af-6b6f358309ff.png">

And I have convert it into an SVG figure

<img width="256" alt="AppIcon" src="https://user-images.githubusercontent.com/110762732/205277584-419b796b-6b8a-492c-92e3-937b0064f597.svg">

Besides, I also made one for Feishu （bytedance-feishu）that only provides png icons by default

<img width="256" alt="AppIcon" src="https://user-images.githubusercontent.com/110762732/205283662-3f9a241f-5456-4282-902d-637508c96824.svg">

**Comment by bikass** [comment]
Hi, Thank you for providing icons.  I updated wechat.svg and added bytedance-feishu.svg

**Comment by Yikai-Liao** [comment]
> Hi, Thank you for providing icons. I updated wechat.svg and added bytedance-feishu.svg

Hi. Don't you feel that the border of these two new icons is too narrow?
![图片](https://user-images.githubusercontent.com/110762732/205442272-30668c3e-6f4d-41ba-afae-18db74dcd0a5.png)

They look strange, especially the  icon of wechat
