### ISSUE TITLE
Chrome Based Browser's Web Apps Missing Icons Issue

### ISSUE THREAD

**Issue by linuxtopia** [bikass/kora#147]
Hello, hello, hello, hello,

Whenever I use the Koro icon pack with KDE, there is always websites web app icon missing. If I use another icon pack then web apps icons showing up properly.

You may try Brave > More Tools > Create Shortcut

and you'll see icons are downloaded under "Edit Application" on right click menu of KDE. Even tough I chose website/app icon, Koro cannot handle it and shows browser's icon.

**Comment by bikass** [comment]
Little bit late with reply, but... :) so, could you provide screenshot I don't use KDE nor Brave?
