### ISSUE TITLE
New icon for CudaText

### ISSUE THREAD

**Issue by eltonfabricio10** [bikass/kora#148]
https://github.com/Alexey-T/CudaText/tree/master/app_res/icon_source

**Comment by bikass** [comment]
There are two icons for CudaText in theme cudatext-512.svg and io.githubcudatext-Qt5.svg 
Or it should be with different name?

**Comment by eltonfabricio10** [comment]
The names are correct, but the original icon has been redesigned.

**Comment by bikass** [comment]
I could only open blend file. Is this correct icon?
![untitled](https://user-images.githubusercontent.com/8824269/222954354-78884316-8447-4f95-9fdd-ccc167e93aef.png)

**Comment by eltonfabricio10** [comment]
![cudatext-512](https://user-images.githubusercontent.com/25956396/222954568-7a195f4b-6398-4d60-904a-391107b89490.png)

new design

**Comment by bikass** [comment]
Ok, I updated icon.

**Comment by eltonfabricio10** [comment]
Thanks
