### ISSUE TITLE
Kora grey not fully applied on folder icon

### ISSUE THREAD

**Issue by xriru** [bikass/kora#152]
![Screenshot from 2023-08-07 01-30-13](https://github.com/bikass/kora/assets/140824018/9df05ee1-6a52-4f96-a8e2-0c37d1d53058)

**Comment by bikass** [comment]
Can't recreate this issue. Good on my side. Did you tried restart PC/ Session? If it is Gnome also you could try clearing icon themes cache (There is .sh file inside themes folder).
