### ISSUE TITLE
Missing Ymuse mime-type icons

### ISSUE THREAD

**Issue by gazsp** [bikass/kora#154]
Hi there! Thank you for these beautiful icons.

The following Ymuse icons use the application defaults instead of the relevant Kora icons:

./scalable/mimetypes/ymuse-album.svg
./scalable/mimetypes/ymuse-stream.svg
./scalable/mimetypes/ymuse-artists.svg
./scalable/mimetypes/ymuse-audio-file.svg
./scalable/mimetypes/ymuse-genres.svg
./scalable/mimetypes/ymuse-albums.svg
./scalable/mimetypes/ymuse-artist.svg
./scalable/mimetypes/ymuse-playlist.svg
./scalable/mimetypes/ymuse-genre.svg
./scalable/mimetypes/ymuse-playlists.svg

Also, it would also be nice to have a proper icon for the app (I'm currently using the Gnome Music app instead).

Regards,
Gaz.

**Comment by bikass** [comment]
Hi, I updated app icon and symelinked mimetype icons.

**Comment by gazsp** [comment]
Wow, that was fast! Thank you so much!
