### ISSUE TITLE
Bad folder icon on x11 plasma

### ISSUE THREAD

**Issue by visualDust** [bikass/kora#156]
Hi. It's of great pleasure to have a beautiful icon pack with your excellent design. I installed kora by clicking on the "get new icons" button in system settings:

![[image](figure: how do I install)](https://github.com/bikass/kora/assets/33346934/fbc5d9cf-b796-41e4-8d1d-1987785bf68c)
figure: how do I install

However, the problem was encountered while applying kora on my laptop:

![[image](figure: what it looks like after applying)](https://github.com/bikass/kora/assets/33346934/ff47c5d2-2009-4817-be33-a34a4abadc82)
figure: what it looks like after applying

The icon changed to normal folder icons when I clicked on the "apply" button and immediately changed to icons above within 0.5 seconds. The screenshot shows what it looks like after applying kora, and as you can see, folder icons were replaced wrongly.

In the folder properties window, it says the icon was not set.

![image](https://github.com/bikass/kora/assets/33346934/ae54dd63-1ea2-4f48-8b69-6e0745d98355)
figure: properties of a random folder

*Since it is questionable that idk if it is a plasma side error, but other icon packages work fine on my computer, so I tend to issue them here.**

System specifics:
```
                   -`                    visualdust@visualdust-archer 
                  .o+`                   ---------------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: KLVC-WXX9 M1050 
               `+oooooo:                 Kernel: 6.5.5-arch1-1 
               -+oooooo+:                Uptime: 5 mins 
             `/:-:++oooo+:               Packages: 1985 (pacman) 
            `/++++/+++++++:              Shell: fish 3.6.1 
           `/++++++++++++++:             Resolution: 2160x1440 
          `/+++ooooooooooooo/`           DE: Plasma 5.27.8 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         WM Theme: Utterly-Round-Dark-Solid 
       -osssssso.      :ssssssso.        Theme: [Plasma], WhiteSur-Dark-solid [GTK2/3] 
      :osssssss/        osssso+++.       Icons: kora [Plasma], kora [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: yakuake 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-10510U (8) @ 4.900GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel CometLake-U GT2 [UHD Graphics] 
 `++:.                           `-/+/   GPU: NVIDIA GeForce MX250 
 .`                                 `/   Memory: 3424MiB / 15733MiB 
```
```
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.5-arch1-1 (64-bit)
Graphics Platform: X11
```

What I've tried:
- logout and re-login
- reboot
- run the script called "create-new-icon-theme.cache.sh" in the project folder
- doing full system updates
- cry

Badnews, these are nice tries but none of them work. Sorry for the trouble, but I like this icon pack, so I would like to find out what is happening.

**Comment by visualDust** [comment]
Plus, my xdpyinfo:

```
screen #0:
  dimensions:    2160x1440 pixels (571x381 millimeters)
  resolution:    96x96 dots per inch
```

I've also acknowledged that kora does not work on another 27' 2560x1440 monitor as well.

**Comment by visualDust** [comment]
I'm not sure whether there is valid icons for folders of all types, since there are less files about folders than those of other icon packs.

![image](https://github.com/bikass/kora/assets/33346934/2edc7f4a-e122-4389-894e-c7352a8c3134)
figure: `.svg` files with names contain 'folder', in kora (left) and in a random icon pack on my laptop (right)

I'm not an expert on it, maybe plasma or dolphin are reading specific icon names for folders. I'm just guessing.

As I mentioned before:
> The icon changed to normal folder icons when I clicked on the "apply" button and immediately changed to icons above within 0.5 seconds.

Here's a screen recording of the phenomenon that might help to explain my bad English expressions:

https://github.com/bikass/kora/assets/33346934/03003d94-d8c7-4f43-8582-aac643c11122

**Comment by bikass** [comment]
Ok, I will look in to it. But can you try downloading and extracting icon pack using terminal not gui?

**Comment by bikass** [comment]
:) thanks for your effort. But can you can you do very simple thing: just download zip from here, unzip it using terminal and place manually to icons folder. I noticed that in plasma if you extract archive using right click and extract here - it doesn't extract properly. 

So I installed KDE neon in VM and looks fine for me:
![Screenshot 2023-09-30 094415](https://github.com/bikass/kora/assets/8824269/0a609762-44b7-4d8a-afe1-156ef022d6c7)

**Comment by visualDust** [comment]
Oh hi, nice to see your response again. I was taking exams as well as fighting against other scholar things some days ago, so I didn't see your comment until now. I will try to extract a zip file into the icon folder, since you cannot reproduce my issues, I think it's not Kora's problem. Therefore, I would close this issue. If I run into other snags, I will check for other reasons. I will report any progress if it is possibly helpful for others who also encounter this issue as well.

**Comment by visualDust** [comment]
Guys I solved the problem by following steps mentioned in a stackexchange post:
[KDE Dolphin stopped using folder icon for regular folders](https://unix.stackexchange.com/questions/463325/kde-dolphin-stopped-using-folder-icon-for-regular-folders)

idk whether it's a workaround or a final solution. I didn't change the default icon of folders in the past, so I'm not actually sure about the reason. Anyway, it works now.
