### ISSUE TITLE
Change text label of Kotlin files from "text" to "kotlin"

### ISSUE THREAD

**Issue by superatomic** [bikass/kora#157]
[The file icon for Kotlin files](https://github.com/bikass/kora/blob/ba51a26f136d5c8ecebb677a7cae0e75b342e1ce/kora/mimetypes/scalable/text-x-kotlin.svg) has label of "text" below the Kotlin logo. This is inconsistent with how other code file formats are labeled, for example, [Python files are labeled as "python"](https://github.com/bikass/kora/blob/ba51a26f136d5c8ecebb677a7cae0e75b342e1ce/kora/mimetypes/scalable/text-x-python.svg), [Java files are labeled as "java"](https://github.com/bikass/kora/blob/ba51a26f136d5c8ecebb677a7cae0e75b342e1ce/kora/mimetypes/scalable/application-java.svg), and so on. I recommended for the label for this file icon to be changed to "kotlin".

**Comment by bikass** [comment]
Hi, Kotlin mimetypes icon has been updated.

**Comment by superatomic** [comment]
Thank you so much! I highly appreciate the quick response.

Just one thing: the text looks a bit off center to me. I can't tell if it's just my eyes or if it's actually a bit to the left, but I think it might be worth taking a look.

**Comment by bikass** [comment]
You were wight :) fixed!

**Comment by superatomic** [comment]
Thank you!
