### ISSUE TITLE
Broken icon in kate

### ISSUE THREAD

**Issue by hazel-bunny** [bikass/kora#158]
![Screenshot_20231024_160730-1](https://github.com/bikass/kora/assets/73038615/67ae1673-ba3a-4e5a-ace1-79a51abb84dd)
 Hi, I maintain kora for Fedora in [my copr](https://copr.fedorainfracloud.org/coprs/hazel-bunny/ports). When I use kate with a dark color scheme and the kora icon theme, the documents icon in the left panel is broken. I'm using kora 1.5.8 in KDE Plasma 5.27.8 running on Fedora 38.

**Comment by bikass** [comment]
Hi, at the moment I can't understand why it is so. Both icons are from same place, but one is light another dark. I tried create just light icon in "symbolic" but no change.
![Screenshot 2023-10-24 164606](https://github.com/bikass/kora/assets/8824269/b1382382-381f-402b-8e43-3176b1ef38c6)
