### ISSUE TITLE
[BUG] Probably wrong icon for ISO files

### ISSUE THREAD

**Issue by lunelovehearn** [bikass/kora#159]
after some updates, I noticed that kora now uses a different "a" icon instead of the .iso icon it was using before.
![Screenshot_20231112_011043](https://github.com/bikass/kora/assets/84490883/eadbae35-244b-48dd-9eb5-175bbaaee9f5)
it used to show a document icon with the radioactive logo and .ico under it.

system info:
Arch Linux kernel 6.5.9
KDE Plasma 5.27.9

**Comment by bikass** [comment]
Hi, Yes it's not supposed to be like this. It is not even a mimetype icon. I checked in gnome - works fine. Can't check on plasma at the moment.
![Screenshot from 2023-11-12 13-19-42](https://github.com/bikass/kora/assets/8824269/caf5fd8a-7258-4e4a-bbb1-66df22b91a84)
Downloaded old version of theme and compared all icons with radioactive symbol are present. But it's not ".ico" it is "cd" under.
