### ISSUE TITLE
Calendar Icon is missing in Ubuntu 23.10

### ISSUE THREAD

**Issue by ihkokil** [bikass/kora#163]
I am using Ubuntu 23.10, but the calendar icon is missing / not working. Please fix the issue. 
![Screenshot from 2023-12-22 17-03-31](https://github.com/bikass/kora/assets/67356814/38ac4b30-c839-454b-9ae2-4b7a997b3b94)

My system details:
![image](https://github.com/bikass/kora/assets/67356814/690dfec0-ae73-4708-8181-39ec368d9116)

**Comment by bikass** [comment]
Yes, it's known issue and has been fixed few weeks ago. Did you checked last commits?

**Comment by ihkokil** [comment]
> Yes, it's known issue and has been fixed few weeks ago. Did you checked last commits?

Thanks. Though I downloaded the files just a week ago, the problem exists for me. The problem is fixed for me now. Thanks for the support.
