### ISSUE TITLE
Alacritty has capital letter

### ISSUE THREAD

**Issue by BWPanda** [bikass/kora#164]
`kora/apps/scalable/Alacritty.svg` starts with a capital letter (uppercase), whereas most other apps start with a lowercase letter. Wondering why this is...

Is it possible to change it to be all lowercase, or can we make a symlink with a lowercase name?

**Comment by bikass** [comment]
Yes, it's not difficult to change. Can you confirm that with lowercase icon will work. Or I could add symlink.

**Comment by BWPanda** [comment]
I'm not using a Desktop Environment, so cannot easily check this. But looking at the `Alacritty.desktop` file it seems that the icon does use an uppercase 'A'. So maybe best to leave as is...

No need to create a symlink either, as I can just specify a different name for the icon and command. So I guess this can be closed.
