### ISSUE TITLE
DE icons and manasarovar

### ISSUE THREAD

**Issue by glitch-method** [bikass/kora#167]
a few icons (i.e. desktop settings: apps/scalable/org.xfce.xfdesktop.svg and a few others, org.xfce.xfwm4-tweaks.svg) are linked to gnome variants ( -> cs-desktop.svg -> cs-desktop-gnome.svg, etc. ), though other DE's variants are present ( apps/scalable/desktop-environment-*.svg, etc. ). can these be fixed? or, if necessary, is it possible to add something like a small script to relink these for other DEs?

also, i don't know how else to contact you; i use and love the manasarovar variant of kora, and would like to use it in an installation script i'm working on. it would be ideal to just pull from git, but as it is the only source i know for the variant is on pling. is it possible to have a manasarovar repo?

( EDIT: thank you so much for your work on this! it may be silly, but finding the right icons reduces anxiety. i really apreciate your efforts! :) )

**Comment by bikass** [comment]
Hi, yes these two icons you mentioned doesn't make sense. Updated them. I do not use xfce, so if there are other icons to change let me know.
Maybe I could make Manasorovar git repo - when I have more time... :)
