### ISSUE TITLE
KDE 6 Support

### ISSUE THREAD

**Issue by snoweuph** [bikass/kora#168]
With KDE 6, Iconpacks are now also used for the system-tray, instead of the plasma theme.

The Icons In the System tray currently look Chaotic and not fitting together, because some Icons are sued as fallback, 
for example the Bluetooth Symbol is a Bluetooth Folder, while the Clipboard Icon seems to be from some fallback.

My Workaround for this currently (because I like this theme) is to just push most of them into the overflow menu, so that I don't see them for most the time:

![image](https://github.com/bikass/kora/assets/76737863/9fdaff2a-7486-494e-8782-d4ccc77f5a0a)

**Comment by bikass** [comment]
I do not use KDE at the moment, but mabye I will look into it some day. So some icons are shown and some are not. For example, clipboard icon is present in theme, but is not used... Mabye different naming. If you want, you can find and fix them.

**Comment by snoweuph** [comment]
Okay, I found out that the new naming of the bluetooth icons got changed to:

![image](https://github.com/bikass/kora/assets/76737863/3025fb50-d229-4afb-b5fa-be92e698f1e8)

**Comment by snoweuph** [comment]
![image](https://github.com/bikass/kora/assets/76737863/2dcefb37-6e45-412f-8a0f-e09c7c9318b0)
![image](https://github.com/bikass/kora/assets/76737863/322e2a06-7e80-4068-a043-88ee2623b5f8)

Bluetooth Icon looks a littlebitthick (I renamed the existing one)

**Comment by snoweuph** [comment]
Okay, Im kindof ggetting into the topic and figuring stuff out, so I started to open up a draft, for this:
https://github.com/bikass/kora/pull/170

**Comment by snoweuph** [comment]
Somebody else made a project based on this allready, which is actievly worked on (Infos in Draft PR above)
