### ISSUE TITLE
missing Disney+ icon

### ISSUE THREAD

**Issue by Pintjebier** [bikass/kora#169]
I love this icon theme as it has so many icons in comparison with other icon theme packs, but I am missing one icon.
Could it be possible to add an icon for Disney+ as there is one for Netflix?

Thanks a million!

**Comment by bikass** [comment]
Could you provide icons name and I will make it?

**Comment by Pintjebier** [comment]
@bikass, thank you so much!!!!
There is an icon called 'netflix-desktop' could you take a copy of that one and change the 'N' to the 'D+' or Disney+ logo from Disney+ with the blue background?

**Comment by bikass** [comment]
Hi, I could do that, but how icon will be called? For ex. : is it disney-plus.svg or something else? I could not find that icon in other themes. But you could take some random icon and check which naming sticks. Do not forget to reload desktop to take effect. Or maybe you have other icon themes with Disney+ icon, then you just look how it called there?

**Comment by Pintjebier** [comment]
sorry for misunderstanding.
disney-plus.svg is just fine ; - )

"Or maybe you have other icon themes with Disney+ icon, then you just look how it called there?"
No, I am using pure your koda icon theme system wide

Thanks a million for all your effort!!!!

**Comment by bikass** [comment]
:) we need to know exact name of icon otherwise it will not work. I just made up this name as example. You can duplicate some other icon, rename and see if it worked.
