### ISSUE TITLE
Failed to load image-missing.svg

### ISSUE THREAD

**Issue by bobblkabb** [bikass/kora#171]
Opened [openSUSE Bug](https://bugzilla.opensuse.org/show_bug.cgi?id=1221964) but rather theme issue. 
Doesn't have the problem with Tokyonight-Dark icon-theme.

**Comment by bikass** [comment]
Apologies, for late response. Is it the same problem with regular Kora or just Kora-pgray? 
Icon image-missing.svg is in the theme. Can you check if you have it in your install?
