### ISSUE TITLE
Add icons for Free Office

### ISSUE THREAD

**Issue by elainefs** [bikass/kora#173]
Could you add icons for Free Office?

The standard icons are awful.

![kora-icons](https://github.com/bikass/kora/assets/70538729/925a45ce-950c-4ec0-be81-2402651624b5)

Making the LibreOffice icons also apply to Free Office would be great.

This icon pack is amazing!

**Comment by bikass** [comment]
Hi, there are FreeOffice icons in theme. But these must have different icon names. I see "...2021". If you could tell exact names of .svg files, I will make a symlinks.

**Comment by elainefs** [comment]
Hi, yes, I am using the FreeOffice 2021. Now that you said it, I went to see that there really are icons for FreeOffice in the 2018 version 😁

So, for 2021 version, the names are these:

Name=FreeOffice 2021 PlanMaker
Icon=application-x-pml21free

Name=FreeOffice 2021 Presentations
Icon=application-x-prl21free

Name=FreeOffice 2021 TextMaker
Icon=application-x-tml21free

**Comment by bikass** [comment]
Hi, I made symlinks. Could you check if everything is fine.

**Comment by elainefs** [comment]
Hi, yes, it worked perfectly, thank you so much!!
