### ISSUE TITLE
Wrong icon for bluetooth on Plasma 6

### ISSUE THREAD

**Issue by evoke0** [bikass/kora#175]
The network folder icon is used for bluetooth instead of the bluetooth icon.

I noticed on Breeze icons that bluetooth icons have a slightly different name, being "network-bluetooth-activated" and not "bluetooth-active".

![Screenshot_20240406_211827](https://github.com/bikass/kora/assets/59049954/65d1da92-304a-44b4-adef-3b3a0d21539e)
![image](https://github.com/bikass/kora/assets/59049954/eb33ef61-d102-4281-a861-b6fee503b413)

**Comment by bikass** [comment]
Hi, it's not only Bluetooth, more icons needs attention for Plasma6 . Need more time for this :)

**Comment by bikass** [comment]
Should be fixed with latest release.
