### ISSUE TITLE
Other colours? 

### ISSUE THREAD

**Issue by zbeeble49** [bikass/kora#178]
Hi,
was wondering if you work on any other colours apart from blue, green & grey?
Wanted an orange variant for my favourite wallpaper (atm), so I put one together.
Looks like this:
![Screenshot_20240414_124548](https://github.com/bikass/kora/assets/36364835/ac99dd41-2ae0-43d2-91f7-e5cbc624fa2f)

Still trying to understand how GitHub works, once I figured this out happy to send you a pull request for "kora-orange" in case you are not working on it anyway...
Timo

**Comment by bikass** [comment]
I'm not planing to make other colors. But it looks nice on your desktop ;)
