### ISSUE TITLE
Suggest to link to ´file-manager.svg´ instead of ´file-manger-blue.svg´ in 'apps'folder

### ISSUE THREAD

**Issue by zbeeble49** [bikass/kora#179]
Hi,
creating the orange variant I have realised there are a couple of blue folder icons in the 'apps' folder. 
Most of them are symlinks pointing to 'file-manager-blue.svg'. 
For (OCD) people like me, suggest to link these 'file-manager.svg' instead: for creating other colour variants only one link needs to be changed.

Love your icon theme ;)
Timo

These are the 37 symlinks in 'apps/scalable' I am thinking of:

./dde-file-manager.svg
./kfm.svg
./fma-config-tool.svg
./gnome-encfs-manager.svg
./org.xfce.thunar.svg
./xfce-filemanager.svg
./thunar-filemanager.svg
./nemo.svg
./mucommander.svg
./d3lphin.svg
./spacefm.svg
./org.kde.plasma.folder.svg
./dolphin.svg
./mc.svg
./system-file-manager.svg
./gnome-commander.svg
./caja-actions.svg
./redhat-filemanager.svg
./org.xfce.filemanager.svg
./org.gnome.nautilus.svg
./file-manager.svg
./user-file-manager.svg
./MidnightCommander.svg
./folder_doc_q4os_startmenu.svg
./nautilus.svg
./nautilus-actions.svg
./org.kde.index.svg
./org.gnome.Files.svg
./spacefm-blue.svg
./org.kde.dolphin.svg
./Thunar.svg
./org.gnome.files.svg
./file-manager-blue.svg
./nautilus-actions-config-tool.svg
./thunar.svg
./org.gnome.Nautilus.svg
./org.xfce.panel.directorymenu.svg

**Comment by bikass** [comment]
Hi, in your case if you modifying folder icons to your liking it makes sense. But I have  different locations blue and gray. Symlinks would source just blue but not gray. Of course now they are blue anyway in gray theme :)
