### ISSUE TITLE
Black icons on Dolphin

### ISSUE THREAD

**Issue by niri-san** [bikass/kora#183]
KDE Plasma 6 - OpenSUSE Tumbleweed

- Dolphin
Search for distrib in icons
It appears on black symbolic icon instead of white.
![Screenshot_20240521_103401](https://github.com/bikass/kora/assets/160327855/25b6b2ac-a82a-4fc8-9a47-22d892159824)

- Dolphin
Rating: ★★★★★
They appears as a grey instead of white.
![Screenshot_20240521_103428](https://github.com/bikass/kora/assets/160327855/da46ca23-b369-44b6-baf1-16846e8f8462)
Unless it means to display such. But, a white symbolic icon would be better viewed.

- Using kora from master branch.

**Comment by niri-san** [comment]
"Search for distrib in icons" is fixed with white icon. Thank you.

Rating stars, are still shown as darker, unless they're supposed to be such?

**Comment by bikass** [comment]
Ok, I found stars - I guess it suppose to be like this :)
![Screenshot from 2024-05-21 22-52-52](https://github.com/bikass/kora/assets/8824269/9afb15ef-8ddb-4013-b807-07d25a8c1259)
Could you find something that has rating stars and show screenshot. Maybe better to make full not just outline...

**Comment by niri-san** [comment]
You're correct, i not rated anything so show it as rating-unrated, once i rated something it appears as rating.

This is completed with the first part completed, and the second part incorrectly by me.

I'll close this. Thank you very much!
