### ISSUE TITLE
KTorrent Tray Icon

### ISSUE THREAD

**Issue by niri-san** [bikass/kora#184]
Plasma 6 - openSUSE Tumbleweed

- KTorrent
Needs a simple symbolic tray icon.
![Screenshot_20240521_125816](https://github.com/bikass/kora/assets/160327855/f660f085-fc96-4cf1-80af-592e6dc39d3b)

- Using kora from master branch.

**Comment by bikass** [comment]
I made symbolic icon. Check if it is working for you

**Comment by niri-san** [comment]
Perfect, replaced quite well.
![Screenshot_20240521_194345](https://github.com/bikass/kora/assets/160327855/8a85c31b-8e05-4e26-8892-75a782f8679b)

This is completed.
