### ISSUE TITLE
[Request Icon] openSUSE Tumbleweed - Distributor Logo

### ISSUE THREAD

**Issue by niri-san** [bikass/kora#185]
Please add icon support for Distro openSUSE Tumbleweed on kora/apps.

Tumbleweed it is used such:
"distributor-logo-Tumbleweed.svg"

**Comment by bikass** [comment]
Made Tumbleweed icon.  There was some kind of contest for new icons... not sure if this one is correct

**Comment by niri-san** [comment]
Your Tumbleweed icon appear correct on KDE Menu > System > Info Center
![Screenshot_20240521_161335](https://github.com/bikass/kora/assets/160327855/d6efe324-c43f-4d7a-ad36-95e191ef56db)
This looks neat and complete, We may close this as completed.

Many thanks for the fast adjustment.
