### ISSUE TITLE
[Request Icon] tsMuxer

### ISSUE THREAD

**Issue by niri-san** [bikass/kora#186]
Please add icon support for app tsMuxer
https://github.com/justdan96/tsMuxer

This app use the icon in such name:
"tsMuxerGUI.svg"

**Comment by bikass** [comment]
Hi, is this the icon tsMuxerGUI/images/icon.png

**Comment by niri-san** [comment]
That's correct icon, the same icon [vinceliuice](https://github.com/vinceliuice/Tela-circle-icon-theme/blob/5a3508a90e96da19bf315eb838066d21209bedb8/src/scalable/apps/tsMuxerGUI.svg#L4) set it for his Tela-circle-icon-theme.

**Comment by bikass** [comment]
Ok, I made the icon.

**Comment by niri-san** [comment]
Closed as completed
