### ISSUE TITLE
[Icon request] Qt6 D-Bus Viewer (D-Bus Debugger)

### ISSUE THREAD

**Issue by niri-san** [bikass/kora#187]
Please provide icon for Qt6 D-Bus Viewer (D-Bus Debugger)
https://doc.qt.io/qt-6.2/qtdbus-index.html

It used on KDE Plasma 6 - Menu > Development

**Comment by bikass** [comment]
Hi there are some qtbusviewer icons in theme. What is the exact name?

**Comment by niri-san** [comment]
Hi, the name is "qdbusviewer6.svg" for KDE Plasma 6.

**Comment by bikass** [comment]
I found that previous had name qdbusviever-qt5 , so I made qdbusviever-qt6.svg . If it doesn't work I will make as you suggested.

**Comment by niri-san** [comment]
Just make a link from "qtdbusviewer.svg" to "qdbusviewer6.svg" will produce icons on the submenu.
![Screenshot_20240522_062739](https://github.com/bikass/kora/assets/160327855/cb469d1e-b376-4697-9a14-513161f0a692)

You already have one for KDE Plasma 5 as "qdbusviewer5.svg", just don't delete yet the 5 version, as it is too early to remove KDE Plasma 5 support for this icon.

**Comment by bikass** [comment]
I made the icon check in new commit.

**Comment by niri-san** [comment]
Just checked, but instead of qtdbusviewer6.svg must be named "**qdbusviewer6.svg**". Needs to be removed that "t".

**Comment by bikass** [comment]
Ok, should be good now.

**Comment by niri-san** [comment]
Yeah, it is fixed. Thank you!

Closed as completed.
