### ISSUE TITLE
KDE Plasma 6 - sidepane/places, to use symbolic icon instead of scalable colors?

### ISSUE THREAD

**Issue by niri-san** [bikass/kora#188]
Hello, on my Dolphin file manager, but not only, even open file dialog on the sidepane/places is using scalable color icons instead of symbolic ones.

![Screenshot_20240530_081255](https://github.com/bikass/kora/assets/160327855/7774773b-9b9e-42ad-a0ac-c80b502360a9)

I think kora/places/symbolic can be used in this case?

On GNOME/Nautilus is been used referring to this [photo](https://images.pling.com/img/00/00/50/97/86/1256209/435abce9c84ab81b729c8a6ae01c8f5a8ccf48ca3d91512044c1a4558c698140fd81.png). I would like it if it were possible to put in KDE?

-Operating System: openSUSE Tumbleweed 20240524
-KDE Plasma Version: 6.0.4
-KDE Frameworks Version: 6.2.0
-Qt Version: 6.7.0
-Graphics Platform: Wayland

-Kora (master)

**Comment by bikass** [comment]
Hi, symbolic icons are in the theme and other DE's using them properly. 
If you find solution let me know :) I don't use KDE.
