### ISSUE TITLE
KDE Plasma 6 - System Settings colored icon instead of symbolic at Titlebar & Application Menu.

### ISSUE THREAD

**Issue by niri-san** [bikass/kora#189]
KDE Plasma 6 - System Settings is using an symbolic icon on Titlebar and Application menu, while there should have been a similar to "systemsettings.svg".
![Screenshot_20240530_092510](https://github.com/bikass/kora/assets/160327855/e39733d7-3f98-4c24-af44-f2321a36c74e)

**Comment by bikass** [comment]
Well, could not find this icon.... If you will provide name I will make it.

**Comment by niri-san** [comment]
The icon name must be "preferences-system" since such it is on location kora/actions/16. 

I just did a renaming "preferences-system.svg" to "preferences-system-.svg" (to put it out of operation temporarily).

I noticed that got the correct title/menu icon.
![Screenshot_20240607_120454](https://github.com/bikass/kora/assets/160327855/93fde263-953b-48b3-92d2-88cb1f5a0628)
However, I am not completely sure renaming, or (removing "preferences-system.svg") is ultimately correct.

We need to see how the other icons packages works on this part.
At the moment i don't know what to say, if i find other options i will update.

**Comment by bikass** [comment]
Ok, I removed icon from actions/16

**Comment by niri-san** [comment]
At the moment, this is fixed, if there is a need for another intervention, We'll open it. Thank you.

**Comment by bikass** [comment]
How do you check icons name and location fro ui. I'm just designer, no much experience in Linux :)

**Comment by niri-san** [comment]
KDE Plasma have a nitty settings that helps a lot finding icons as image, names, and related categories.
I am making a video presentation
https://streamable.com/emb8nv

If you can't see it within two days let me know to make another preview.

**Comment by bikass** [comment]
Ok, I see. Thank you very much :)
