### ISSUE TITLE
KDE Plasma 6 - Kora-Grey Dark Arrows

### ISSUE THREAD

**Issue by niri-san** [bikass/kora#191]
On kora-pgrey the arrow icon of Application Menu appears as darker instead of white.
![Screenshot_20240531_180847](https://github.com/bikass/kora/assets/160327855/ca680610-d020-408e-b530-82ae55863d38)

**Comment by niri-san** [comment]
Indeed strange,

kora
![Screenshot_20240607_124321](https://github.com/bikass/kora/assets/160327855/63adff13-37b3-4946-97f9-d3989cfc04b9)

kora-pgrey
![Screenshot_20240607_124502](https://github.com/bikass/kora/assets/160327855/0dfd84ee-c076-40b9-915c-dfe36b613d91)

By the way, the "preferences-system.svg" must be removed aswell from kora-pgrey.

We'll leave this open, if anyone has a solution, you or i find something.

**Comment by bikass** [comment]
"actions" in kora-pgrey also linked to main Kora, so should work

**Comment by niri-san** [comment]
Please see in video presentation.
[Screencast_20240607_130627.webm](https://github.com/bikass/kora/assets/160327855/d2d02d81-11b2-4c45-bfad-3cb4b84390d7)

**Comment by niri-san** [comment]
I tried to find any naming anomalies or anything at index.theme, but didn't find anything suspicious. I'm closing this by using kora as my main selection, the grey for me have no priority at the moment. If anyone comes with any suggestion or solution, feel free to open it or open another ticket.
