### ISSUE TITLE
File's/folder's indicators (?) are barely visible in Dark Mode.

### ISSUE THREAD

**Issue by ASHGOLDOFFICIAL** [bikass/kora#192]
I don't know how are they called but I'm talking about small icons that indicate whether file//folder is a link, whether I have permissions to modify them, etc. On the screenshot `.steam*`, `.tmux.conf` and `.zshenv` have them.
![image](https://github.com/bikass/kora/assets/104313094/adf07c7c-cc7c-4d54-8e9e-4b36e96a4942)

With Dark Mode off, everything is okay.
![image](https://github.com/bikass/kora/assets/104313094/f5782160-92c4-4d15-9950-503fbe7a7367)

I think there should be better contrast.

**Comment by bikass** [comment]
Hi, unfortunately but they will be as is for now. They look good on DE I use in dark mode.
