### ISSUE TITLE
[Icon Request] Please add icons for some new Gnome apps

### ISSUE THREAD

**Issue by user1-github** [bikass/kora#197]
[Camera](https://flathub.org/apps/org.gnome.Snapshot) - Gnome camera app (Suggestion - maybe use [this icon](https://github.com/bikass/kora/blob/master/kora/apps/scalable/applets-screenshooter.svg) for Camera?)

[Papers](https://flathub.org/apps/org.gnome.Papers) - Document viewer

[Showtime](https://flathub.org/apps/org.gnome.Showtime) - Video player

[Decibels](https://flathub.org/apps/org.gnome.Decibels) - Simple audio player

[Ptyxis](https://flathub.org/apps/app.devsuite.Ptyxis) - New terminal app

**Comment by bikass** [comment]
Hi, could you provide icon names. Camera - I see same icon org.gnome.Snapshot.svg

**Comment by user1-github** [comment]
Awesome, thank you
