### ISSUE TITLE
Please add an icon for folders related to 3D printing

### ISSUE THREAD

**Issue by humlg** [bikass/kora#199]
None of the current icons display a file with a label resembling neither a 3D object, or a 3D printer. Even a CNC machine, or anything of that kind. Maybe something like this could be an interesting pictogram on the folder icon? Or just a cube, that would also work.

![image](https://github.com/user-attachments/assets/5a1c25d2-41f5-47c4-927c-b6c1aac64c93)

**Comment by bikass** [comment]
Hi, sure, I can make it. What is the name of this icon?

**Comment by bikass** [comment]
Hi I made icon. Usually you need to know exact name of icon. Because now it will not appear anywhere. It could be assigned just manually.
