### ISSUE TITLE
Please give Icons color that work with Solarized Dark theme

### ISSUE THREAD

**Issue by blueray453** [bikass/kora#201]
I think the following colored icons will go great with the solarized dark theme.

Blue     #268bd2
Cyan	#2aa198
Yellow	#b58900
Orange	#cb4b16
Green	#859900

I found that you are using Yellow and Green but i think the color codes does not match.

We would be glad if you kindly add at least Cyan (#2aa198) in the theme.

**Comment by bikass** [comment]
Hi, I'm not making more color variants. Sorry about that!
