### ISSUE TITLE
How do I set Nextcloud Folder Icon?

### ISSUE THREAD

**Issue by faxotherapy** [bikass/kora#202]
Hi, I have a Nextcloud folder, but there's no icon on it, just plain folder. How do I set the Kora Nextcloud icon? Thank you.

EDIT: I forgot to mention my DE: Xfce

**Comment by D3SOX** [comment]
I'm pretty sure that depends on your file manager, not DE.
In Dolphin there's a UI to do that. It creates a `.directory` file inside the folder with the contents like
```
[Desktop Entry]
Icon=folder-onedrive
```
I just tested with Thunar and it doesn't apply that icon and I think that it doesn't support custom folder icons.

**Comment by faxotherapy** [comment]
Thanks for your reply. In fact, it's very much indeed so. Here's the last [nail in the coffin](https://forum.xfce.org/viewtopic.php?id=17051).
