### ISSUE TITLE
[Bug] KDE Application Launcher Menu Icons 

### ISSUE THREAD

**Issue by ZorinFoss** [bikass/kora#204]
Hi,

After KDE plasma v6.2 released, KDE application launcher menu icons need some fixes.

![Screenshot_20241024_150110](https://github.com/user-attachments/assets/6fb4a293-a6c3-4433-a5ad-97ef92481c7d)

Thanks

**Comment by bikass** [comment]
I don't use KDE at the moment. So if you could find out names of these icons, would make may life easier :)

**Comment by ZorinFoss** [comment]
Here all categories icons from breeze icons
[32.zip](https://github.com/user-attachments/files/17507801/32.zip)

**Comment by ZorinFoss** [comment]
The icon's names seem it's correct, but why it doesn't work!!!

**Comment by bikass** [comment]
OK so I was wondering as well.... seems like we need small icons not the full ones. And symbolic icons where missing :)
![Screenshot 2024-10-24 195024](https://github.com/user-attachments/assets/efcc1db5-beb3-44b9-a00e-235581ab2bc2)

**Comment by ZorinFoss** [comment]
This is weird!, breeze icon theme uses color icons

**Comment by bikass** [comment]
Maybe there is something to change in index file.

**Comment by D3SOX** [comment]
These were the related MRs for that. It was also changed in Discover.
https://invent.kde.org/plasma/plasma-desktop/-/merge_requests/2415
https://invent.kde.org/plasma/discover/-/merge_requests/888

It looks like they've just appended "-symbolic" to everything.

**Comment by bikass** [comment]
So it should be that way, then (symbolic icons)? Only one icon I see in discover that could be replaced: Plasma addons
