### ISSUE TITLE
[Icon Request] Please add an Icon for zen browser (To keep the icon size consistent)

### ISSUE THREAD

**Issue by J4N4RI** [bikass/kora#206]
![ZenLogo2024](https://github.com/user-attachments/assets/9861499c-4ad7-4157-a5da-2b440a16a7ab)

**Comment by bikass** [comment]
What is correct name of this icon. I Already have it in theme as zen.svg and zen-browser.svg

**Comment by noodlejetski** [comment]
Zen Browser has recently redesigned their logo and got rid of the Z: https://github.com/zen-browser/branding

**Comment by bikass** [comment]
Oh, I made this icon a while ago, just forgot to push :) Just My icon is black and white. Is this orange how it supposed to be?

**Comment by noodlejetski** [comment]
they offer multiple colour versions, but I _think_ the black and white one is the default.
