### ISSUE TITLE
Please make an icon for the gnome camera

### ISSUE THREAD

**Issue by J4N4RI** [bikass/kora#208]
Makes the icon theme more consistent.

![net flyingpimonster Camera](https://github.com/user-attachments/assets/ee3f67f0-d6af-4823-b3e5-5773ff16f086)

**Comment by bikass** [comment]
There is such icon called org.gnome.Snapshot.svg Doesn't it show up to you?

**Comment by J4N4RI** [comment]
> There is such icon called org.gnome.Snapshot.svg Doesn't it show up to you?

nope

**Comment by bikass** [comment]
works for me
file:///home/oo/Pictures/Screenshots/Screenshot%20from%202024-12-15%2011-43-04.png
