### ISSUE TITLE
Buttons that can be improved in some applications

### ISSUE THREAD

**Issue by xzj8b3** [bikass/kora#65]
![Schermata da 2020-01-05 15-58-47](https://user-images.githubusercontent.com/26720956/71781973-0fedbe80-2fd5-11ea-8d7e-a0fc0e76790a.png)
You can make buttons for dark theme, but they can also be visible in white 

As the image shows in KeepassXC bar buttons are not visible and also happens with other applications.....

A pity because it clashes with the excellent work done on the theme that remains the best!!!

Thanks again and Buonefeste

**Comment by bikass** [comment]
Hi, did you tried korla-light?

**Comment by xzj8b3** [comment]
> Ciao, hai provato Korla Light?

Of course, Grey tried it too, but none of the three of them see them.

**Comment by Digitalone1** [comment]
> ![Schermata da 2020-01-05 15-58-47](https://user-images.githubusercontent.com/26720956/71781973-0fedbe80-2fd5-11ea-8d7e-a0fc0e76790a.png)
> You can make buttons for dark theme, but they can also be visible in white
> 
> As the image shows in KeepassXC bar buttons are not visible and also happens with other applications.....
> 
> A pity because it clashes with the excellent work done on the theme that remains the best!!!
> 
> Thanks again and Buonefeste

What desktop theme are you using? Light for applications and dark for panels?

**Comment by xzj8b3** [comment]
> > ![Schermata dal 2020-01-05 15-58-47](https://user-images.githubusercontent.com/26720956/71781973-0fedbe80-2fd5-11ea-8d7e-a0fc0e76790a.png)
> > Puoi creare pulsanti per il tema scuro, ma possono anche essere visibili in bianco
> > Come mostra l'immagine nella barra KeepassXC, i pulsanti non sono visibili e si verificano anche con altre applicazioni .....
> > Un vero peccato perché si scontra con l'ottimo lavoro svolto sul tema che rimane il migliore !!!
> > Grazie ancora e Buonefeste
> 
> Quale tema del desktop stai usando? Luce per applicazioni e buio per pannelli?

![Personalizzazioni di GNOME_001](https://user-images.githubusercontent.com/26720956/82265850-55999b00-9968-11ea-9a39-66d0eba4b09c.png)

I'm using this as a theme, which would be good for "Korla" normal, too bad that if a software has white screens the buttons are no longer visible ... and I had to use Korla light although not suitable on dark themes ...

An extra variant with buttons in a different shade????

**Comment by Digitalone1** [comment]
Something like korla-dark-panel? Dark theme for applications and light for panel?

**Comment by Digitalone1** [comment]
So dark icons for applications and light for panel? Did you try korla-light?

**Comment by xzj8b3** [comment]
> Quindi icone scure per applicazioni e luce per pannello? Hai provato korla-light?

 If you look at the image I'm using korla,light ...yes in the white windows now I see the black buttons but with gnome shell its icons are made for a white panel...

It would take a variant that could be better for Gnome Shell that in dark themes has some white windows that using korla buttons are no longer visible...

For example software icons in the panel tray on a dark color are not good even light (they are dark).

**Comment by xzj8b3** [comment]
> Quindi icone scure per applicazioni e luce per pannello? Hai provato korla-light?

korla that's fine... but on white windows white buttons are lost... another color would be nice...

**Comment by Digitalone1** [comment]
> > Quindi icone scure per applicazioni e luce per pannello? Hai provato korla-light?
> 
> If you look at the image I'm using korla,light ...yes in the white windows now I see the black buttons but with gnome shell its icons are made for a white panel...
> 
> It would take a variant that could be better for Gnome Shell that in dark themes has some white windows that using korla buttons are no longer visible...
> 
> For example software icons in the panel tray on a dark color are not good even light (they are dark).

No, you're using `korla-light-panel`, not `korla-light`. 

`korla-light` is made for light applications and dark panel which should be good for your environment. 

Post a screenshot with `korla-light` theme.

**Comment by xzj8b3** [comment]
> > > Quindi icone scure per applicazioni e luce per pannello? Hai provato korla-light?
> > 
> > 
> > Se guardi l'immagine che sto usando korla, la luce ... sì nelle finestre bianche ora vedo i pulsanti neri ma con gnome le sue icone sono fatte per un pannello bianco ...
> > Ci vorrebbe una variante che potrebbe essere migliore per Gnome Shell che nei temi scuri ha alcune finestre bianche che usando i pulsanti di korla non sono più visibili ...
> > Ad esempio, le icone del software nella barra delle applicazioni su un colore scuro non sono buone nemmeno se chiare (sono scure).
> 
> No, stai usando `korla-light-panel`, no `korla-light`.
> 
> `korla-light` è fatto per applicazioni chiare e pannelli scuri che dovrebbero essere buoni per il tuo ambiente.
> 
> Pubblica uno screenshot con `korla-light`tema.

Yes, you're right, but I've noticed and it's much better.
