### ISSUE TITLE
Dark missed call notification icon in light panel theme

### ISSUE THREAD

**Issue by Digitalone1** [bikass/kora#66]
As the title says.

![KDE_connect_missed_call](https://user-images.githubusercontent.com/25790525/71889000-8ad3e800-3141-11ea-82bf-63a3f47254cc.png)

**Comment by xzj8b3** [comment]
> Come dice il titolo.
> 
> ![KDE_connect_missed_call](https://user-images.githubusercontent.com/25790525/71889000-8ad3e800-3141-11ea-82bf-63a3f47254cc.png)

In some people they are not very visible especially in Gnome Shell themes where dark themes are used, but also with white windows!!

It would take a variant to be visible on both!!!!

After the last update also the Rhythmbox icon seems to have disappeared!!!!

**Comment by Digitalone1** [comment]
@bikass maybe I found the reason.

Missing call icon is missing in korla-light.

A search for call in korla-light:
![Screenshot_20200506_153300](https://user-images.githubusercontent.com/25790525/81183218-2b7ecb00-8faf-11ea-89da-9ac2ef4d2109.png)

Same search in korla:
![Screenshot_20200506_153433](https://user-images.githubusercontent.com/25790525/81183232-2faae880-8faf-11ea-8ecf-d8d16c85f487.png)

I think it relies on Breeze and that's why it's shown white. See also that call-start-symbolic have different styles

**Comment by xzj8b3** [comment]
> As the title says.
> 
> ![KDE_connect_missed_call](https://user-images.githubusercontent.com/25790525/71889000-8ad3e800-3141-11ea-82bf-63a3f47254cc.png)

Yes, but it would take a segment mode on dark themes but also with white parts.

It is the best theme without a doubt, personally I would also change window buttons (close, enlarge, minimize) with something more beautiful ... it's the best, perfect it that's great!!

**Comment by bikass** [comment]
If icons in "symbolic' folder I can change them and add (I recently remade all these icons). "actions/scalable" and 'panel' icons are from Papirus theme. They have code that I don't know any automatic way to make them.
Some icons changes from dark to light and some don't. I wonder if it would help if in status/symbolic We made dark icons (now they are symelinked to korla/status.symbolic)? 
Does someone knows some way or script to change color to all icons?

**Comment by Digitalone1** [comment]
You can change color with atom text editor. It should be easy since svg are text files.

Open a project on korla folder, then search for a color and replace it with another one.

Which color you have to change in particular?

**Comment by bikass** [comment]
@xzj8b3 And regarding minimize, close buttons I can change them they are in actions symbolic. But not realy sure into what design. It's just dash, square and x

**Comment by bikass** [comment]
WE could try changing korla-light/status/symbolic. But it is symelinked so links needs to be redone too.
Dark icons from Papirus has this color #444444

**Comment by Digitalone1** [comment]
So you have to change #444444 color into another color? Only inside korla-light/status/symbolic?

**Comment by xzj8b3** [comment]
> @xzj8b3 And regarding minimize, close buttons I can change them they are in actions symbolic. [ E per quanto riguarda i pulsanti minimizza, chiudi posso cambiarli, sono in azioni simboliche.] But not realy sure into what design. [ Ma non sono sicuro di quale design.] It's just dash, square and x [ È solo trattino, quadrato e x]

Cuter, too cute theme for such simple buttons!!!

**Comment by xzj8b3** [comment]
> You can change color with atom text editor. It should be easy since svg are text files.
> 
> Open a project on korla folder, then search for a color and replace it with another one.
> 
> Which color you have to change in particular?

That's not the point.

Some themes use both black and white

and no more icons are shown in the button or right button menu.

The Top would be a blue variant where you can see how it was done for the one with gray folders!!

Otherwise we can release please enter a small text file with all possible variables can be done via gedit or terminal please!!!

**Comment by Digitalone1** [comment]
> Otherwise we can release please enter a small text file with all possible variables can be done via gedit or terminal please!!!

Sorry, I don't get what you mean.

**Comment by xzj8b3** [comment]
> > Otherwise we can release please enter a small text file with all possible variables can be done via gedit or terminal please!!!
> 
> Sorry, I don't get what you mean.

![Selezione_004](https://user-images.githubusercontent.com/26720956/81825936-87a99800-9537-11ea-8392-2e764f123832.png)

![Selezione_003](https://user-images.githubusercontent.com/26720956/81825981-9001d300-9537-11ea-85d0-185296ff9342.png)
What I meant is a more visible version even in those cases because if I change, I don't see any more buttons....

Instead even with Gnome Shell are born excellent themes that with your icons are fantastic is creating a variant of the buttons that is visible correctly in both cases would be exceptional ... with buttons for the prettiest windows ....

Now I use only your icons ... if you solve these small details would deserve a theme repository ... no more beautiful you were great!!

**Comment by xzj8b3** [comment]
> > > Otherwise we can release please enter a small text file with all possible variables can be done via gedit or terminal please!!!
> > 
> > 
> > Sorry, I don't get what you mean.
> 
> ![Selezione_004](https://user-images.githubusercontent.com/26720956/81825936-87a99800-9537-11ea-8392-2e764f123832.png)
> 
> ![Selezione_003](https://user-images.githubusercontent.com/26720956/81825981-9001d300-9537-11ea-85d0-185296ff9342.png)
> What I meant is a more visible version even in those cases because if I change, I don't see any more buttons....
> 
> Instead even with Gnome Shell are born excellent themes that with your icons are fantastic is creating a variant of the buttons that is visible correctly in both cases would be exceptional ... with buttons for the prettiest windows ....
> 
> Now I use only your icons ... if you solve these small details would deserve a theme repository ... no more beautiful you were great!!



> WE could try changing korla-light/status/symbolic. But it is symelinked so links needs to be redone too.
> Dark icons from Papirus has this color #444444

explain better or put details in a readme file in the next version, I put an example in a comment below ... if I change on white I don't see those buttons anymore ... While on Bleachbit you can see little ... how can I resole??

I used Korla-light-panel

**Comment by xzj8b3** [comment]
> WE could try changing korla-light/status/symbolic. But it is symelinked so links needs to be redone too.
> Dark icons from Papirus has this color #444444

It is not possible to create a variant  Korla-dark-light-panel ??

![Selezione_004](https://user-images.githubusercontent.com/26720956/81828274-e96b0180-9539-11ea-8f31-78de78932dc2.png)

For example, to make more visible button with similar gtk

![Selezione_003](https://user-images.githubusercontent.com/26720956/81828416-10c1ce80-953a-11ea-9a45-aa26b0b2b0a1.png)

but that it remains so on paper...

![Selezione_005](https://user-images.githubusercontent.com/26720956/81828655-4f578900-953a-11ea-8cda-b510cd07eeef.png)

And maybe better buttons?

It's the best theme with these little additions would achieve perfection... I've only been using korla for a long time now... wonderful!!!!!

**Comment by Digitalone1** [comment]
This should be fixed with the last pull request.

> > > Otherwise we can release please enter a small text file with all possible variables can be done via gedit or terminal please!!!
> > 
> > 
> > Sorry, I don't get what you mean.
> 
> ![Selezione_004](https://user-images.githubusercontent.com/26720956/81825936-87a99800-9537-11ea-8392-2e764f123832.png)
> 
> ![Selezione_003](https://user-images.githubusercontent.com/26720956/81825981-9001d300-9537-11ea-85d0-185296ff9342.png)
> What I meant is a more visible version even in those cases because if I change, I don't see any more buttons....
> 
> Instead even with Gnome Shell are born excellent themes that with your icons are fantastic is creating a variant of the buttons that is visible correctly in both cases would be exceptional ... with buttons for the prettiest windows ....
> 
> Now I use only your icons ... if you solve these small details would deserve a theme repository ... no more beautiful you were great!!

I don't see any issue wih your screenshot. Inactive icons are greyd, but still visible.

**Comment by Digitalone1** [comment]
@xzj8b3 Sorry I deleted a messege of yours by mistake.

Anyway, that is my reply:

> It is not possible to create a variant  Korla-dark-light-panel ??

![Selezione_004](https://user-images.githubusercontent.com/26720956/81828274-e96b0180-9539-11ea-8f31-78de78932dc2.png)

If you use korla-light-panel, you have to use a light theme. Can't you change your desktop theme?
Or if you're using a desktop dark theme, switch to korla.
