### ISSUE TITLE
Why name change.

### ISSUE THREAD

**Issue by algent-al** [bikass/kora#99]
I am curious about why did you change the name?

**Comment by bikass** [comment]
Did spelling mistake when created theme. I wanted to correct name for a long time, just didn't knew how.
Apologies for inconvenience.

**Comment by algent-al** [comment]
Name `korla` was fine in my opinion. What conserns me is if it will break existing installations for at least solus users when transiting from `korla` to `kora`.

**Comment by bikass** [comment]
Maybe you can fork it with korla name. Anyway there is not going to be much changes, just some app icons. I already gave up making it original theme.

**Comment by Digitalone1** [comment]
> Name `korla` was fine in my opinion. What conserns me is if it will break existing installations for at least solus users when transiting from `korla` to `kora`.

The icon theme should be changed from the system settings and the installation process needs some modification since the path is changed.

But this should be done only when the new release will come out.

**Comment by Digitalone1** [comment]
@bikass please, before to release the new version, mention me here so I can make a test on Arch Linux and see if everything is okay, so the release can be made safely then.

**Comment by bikass** [comment]
Ok, I'll drop a line here.
There is one more thing :) I'm working on 'panel' icons. And because I don't know how batch resize icons, I left just one size - folder panel/16

**Comment by D3SOX** [comment]
Can you make a new release with the new name? I will create a new AUR package with the name of `kora-icon-theme` and merge it with my old package.

**Comment by Digitalone1** [comment]
@D3SOX The name has been already changed. The new release will come out when it's ready.

**Comment by D3SOX** [comment]
I know but the folders in the current release are still named korla

**Comment by bikass** [comment]
Does anybody know how this icon is called, cant find it?
![app_icon](https://user-images.githubusercontent.com/8824269/103285562-24e20f80-49e7-11eb-9f08-cd6de7b2d352.jpg)

**Comment by algent-al** [comment]
> 
> 
> Does anybody know how this icon is called, cant find it?
> ![app_icon](https://user-images.githubusercontent.com/8824269/103285562-24e20f80-49e7-11eb-9f08-cd6de7b2d352.jpg)

There is already an issue about this. https://github.com/bikass/kora/issues/70

But still you have to verify if it is that icon.

**Comment by bikass** [comment]
Thank you! So, that was preferences-desktop-apps-symbolic.svg

**Comment by D3SOX** [comment]
I created a AUR package with the new name https://aur.archlinux.org/packages/kora-icon-theme-git/

**Comment by bikass** [comment]
@D3SOX Thank you!
Does anyone uses Prof-Gnome-Dark-3.6 shell theme? In case you are, and don't like those three bubbles to close windows, I made small changes. And those icons kind-of animates.
![Screenshot from 2020-12-29 17-38-33](https://user-images.githubusercontent.com/8824269/103296226-54e8dd00-49fe-11eb-8429-652f5ba988ee.jpg)

**Comment by algent-al** [comment]
> Thank you! So, that was preferences-desktop-apps-symbolic.svg

Yeah, I did a search on my Solus system, only Adwaita Icon Theme has that file.
`Package adwaita-icon-theme has file /usr/share/icons/Adwaita/scalable/apps/preferences-desktop-apps-symbolic.svg`

**Comment by bikass** [comment]
@Digitalone1 Ok, so I finished 'panel' icons, you can test theme. I will be releasing someday in the beginning of January.

**Comment by Digitalone1** [comment]
I'm checking in the next hours and let you know.

**Comment by Digitalone1** [comment]
I made some adjustments. Tested on my system, it's working without issue, at least the korla light which I use daily.

I'll test also the others, but I don't know where to test status and places icons. Most of the applications I use don't show them.

**Comment by bikass** [comment]
OK, cool should be fine.

**Comment by Digitalone1** [comment]
But please next time when you change an icon in kora, change also the light version in kora-light, many of them was missing. I had to copy korla places in korla-light and replace `#dfdfdf` color with `#44444`. Thank God atom editor does this in 2 minutes. :)

**Comment by bikass** [comment]
Ok, thank you :)

**Comment by algent-al** [comment]
> Ok, I'll drop a line here.
> There is one more thing :) I'm working on 'panel' icons. And because I don't know how batch resize icons, I left just one size - folder panel/16

This is bad for Budgie Desktop. There is already an issue about this.

**Comment by algent-al** [comment]
It wasn't that easy but I think i should keep the name `korla` for Solus users.
This can be the new package.yml file https://hastebin.com/agigebijos.properties

**Comment by algent-al** [comment]
The theme is working without any issue on Solus, by keeping old name.

**Comment by bikass** [comment]
Hi, ok cool. Thanks!

**Comment by algent-al** [comment]
Closing this issue, since I don't have any issue on Solus.

**Comment by murlakatamenka** [comment]
> Did spelling mistake when created theme. I wanted to correct name for a long time, just didn't knew how.
> Apologies for inconvenience.

Oh man, I like `korla` name so much. It has a call letter / sound `l` that sounds so nicely here.

Came here cause there is no AUR package anymore, it got renamed too.

Thank you very much for the icons ❤️
